artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip # data source location
  local_data_file: artifacts/data_ingestion/data.zip  # storage of .zip file in local
  unzip_dir: artifacts/data_ingestion